language: python

matrix:
  include:
  - os: linux
    dist: xenial
  - os: linux
    dist: bionic
  - os: osx
    language: generic
  - os: windows
    language: generic

addons:
  apt:
    packages:
    - clang
    - clang-format
    - clang-tidy
    - uncrustify
    - cppcheck
branches:
  only:
  - python
script: "./tests/run_tests"
