version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-and-test:
    executor: win/default
    steps:
      - checkout
      - run:
          command: ./tests/run_tests.ps1
          shell: powershell.exe
          name: powershell_test
workflows:
  main:
    jobs:
      - build-and-test
